### ISSUE TITLE
Le tag upgrade ne lance pas les migrations et la construction du front

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/ansible-zestedesavoir#10]
En déployant la prod j'ai remarqué que les migrations n'avaient pas été lancées, et que le front n'était pas à jour.

**Comment by Situphen** [comment]
Est-ce qu'il ne faudrait pas rajouter ce bout de code : 

```yml
tags:
  - bootstrap
  - upgrade
```

pour : 

-  https://github.com/zestedesavoir/ansible-zestedesavoir/blob/master/roles/app/tasks/frontend.yml#L7
-  https://github.com/zestedesavoir/ansible-zestedesavoir/blob/master/roles/app/tasks/frontend.yml#L12
- https://github.com/zestedesavoir/ansible-zestedesavoir/blob/master/roles/app/tasks/main.yml#L167
- https://github.com/zestedesavoir/ansible-zestedesavoir/blob/master/roles/app/tasks/main.yml#L213

?
