### ISSUE TITLE
Correction du rôle LaTeX

### ISSUE THREAD

**Issue by sandhose** [zestedesavoir/ansible-zestedesavoir#4]
Le rôle LaTeX actuellement installe les paquets texlive de base, télécharges les polices qu'il faut, et clone `latex-template` dans `/usr/local/share/texmf/latex-template`. Sauf que:

 - on dirait qu'il manque des paquets (`asmsymb` par exemple ?)
 - il trouve pas `zmdocument.cls` (un mauvais path ?)

Il me faudrait plus d'info pour régler proprement ces deux problèmes. cc @Heziode @artragis

**Comment by Heziode** [comment]
Dans le repo **latex-template** il y a un répertoire [scripts](https://github.com/zestedesavoir/latex-template/tree/master/scripts) à la racine qui contient tous les scripts nécessaires pour installer texlives et les paquets requis.
Tu peux peut-être les faire exécuter par ton process ou t'en inspirer (si ce n'est pas déjà fait) pour tout installer. 

*Je ne peux pas aider davantage ces temps ci, j'ai pas trop le temps.*

**Comment by pierre-24** [comment]
En particulier (je connais pas trop ansible donc je vois pas ou il est installé), il est important d'utiliser un [`texlive.config`](https://github.com/zestedesavoir/latex-template/blob/master/scripts/texlive.profile) et de bien mettre une variable `TEXMFLOCAL`: c'est là qu'il faut ensuite mettre le `zmdocument.cls`, normalement. Par ailleurs, et comme tu peux le voir dans le script d'[installation travis](https://github.com/zestedesavoir/latex-template/blob/master/scripts/install_texlive.sh), y'a une pelletée de package à rajouter (variable `EXTRA_PACKAGES`, installation de ceux-ci se faisant [ligne 31 et 32](https://github.com/zestedesavoir/latex-template/blob/master/scripts/install_texlive.sh#L31-L32)).

Si tu savais m'indiquer ou tu installe texlive, je peux peut être t'aider.

**Comment by artragis** [comment]
il faut aussi faire `sudo texhash` après avoir installé le latex-template ainsi que faire un clone récursif pour avoir le paquet lualatex

ou alors utiliser le script d'installation travis que j'avais modifié justement pour être utilisable en local.

**Comment by sandhose** [comment]
Hm, je suis pas *super fan* de l'installation de texlive en dehors d'apt. À la base je l'avais fait le script sur travis pour rendre l'install plus rapide, mais pas une installation propre.

Normalement j'ai une install qui fonctionne à peu près maintenant, mais j'ai une erreur en compilant le fichier `test.tex`:

```
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
! Undefined control sequence.
l.337   \pdflinkmargin
                    1pt %
```

https://gist.github.com/sandhose/8de18a2fd6d57b7bf9a515fe06adb9fe

**Comment by sandhose** [comment]
Aussi, j'ai pas pu installer les paquets `glossaries` (pas installable en mode utilisateur) et `ifthen` (pas dans les dépôts).

**Comment by artragis** [comment]
au pire texlive-full devrait tout contenir logiquement.

**Comment by pierre-24** [comment]
Chui d'accord avec artragis, même si c'est un peu bourrin. Sinon, glossaries est dans `texlive-latex-extra` (dont tu as de toute façon, besoin, je crois). Pour ifthen, ça m'étonne un peu vu que le script d'instal travis l'installe à priori sans souci ?!?

**Comment by artragis** [comment]
pour faciliter l'import des images qui sont en local, peux-tu ajouter, dans ce rôle une commande qui s'assure que le lien symbolique entre `/media/galleries`->`/opt/zds/data/media/galleries` est fait?
