### ISSUE TITLE
Mise à jour de BorgBackup

### ISSUE THREAD

**Issue by Situphen** [zestedesavoir/ansible-zestedesavoir#58]
Actuellement on utilise BorgBackup 1.1.9 qui est une assez vieille version. Il faudrait passer rapidement à la version 1.1.17 puis un peu plus tard à la version 1.2.x quand elle aura été éprouvée. Il faudra probablement installer les binaires directement depuis le site web de BorgBackup étant donné que les dépôts de Debian ne proposent pas les versions à jour et ce, à la fois sur la bêta et la prod.

[Binaires de BorgBackup](https://github.com/borgbackup/borg/releases)
[Changelog de BorgBackup](https://borgbackup.readthedocs.io/en/stable/changes.html#change-log)

**Comment by philippemilink** [comment]
Fait.

J'ai précisé dans la doc comment j'ai fait : 38b851eac197a6fefd9ba4867a8fffd91552e874

On verra une fois qu'on aura des sauvegardes externes si on peut passer à la version 1.2.
