### ISSUE TITLE
Télécharger et installer les données GeoLite2 automatiquement

### ISSUE THREAD

**Issue by Arnaud-D** [zestedesavoir/ansible-zestedesavoir#59]
Une [PR](https://github.com/zestedesavoir/zds-site/pull/6409) sur le dépôt principal vise à retirer les données GeoLite2 du dépôt. Il faudra donc les télécharger et les installer dans le cadre du déploiement.

Bien que ce soit faisable manuellement, le mieux est de l'automatiser. Il y a différentes options :

* un updater proposé par l'éditeur,
* du téléchargement direct, toujours depuis le site de l'éditeur.

La [documentation](https://dev.maxmind.com/geoip/updating-databases) raconte tous les détails.

Voir aussi [#6384](https://github.com/zestedesavoir/zds-site/issues/6384).

**Comment by philippemilink** [comment]
Les scripts nécessaires pour mettre à jour automatiquement les données de GeoLite ont été ajouté au dépôt avec le commit b8798279b4bd06b4e8553fec0e4bb7061b26b0f0.

Le commit correspondant dans zds-site est https://github.com/zestedesavoir/zds-site/commit/d23dbc681168a446a47789a00985f4cc74d07d0e.
